Update dependency ws to v8 (#14)
* Update dependency ws to v8

* change URL due to protocol error

SyntaxError: The URL's protocol must be one of "ws:" ...

Co-authored-by: Renovate Bot <bot@renovateapp.com>
Co-authored-by: Carl Walsh <darthwalsh@gmail.com>